# Generated by Django 4.0.3 on 2022-04-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Present_Designation', models.CharField(max_length=200)),
                ('Whether_HOD', models.BooleanField(default=False)),
                ('Highest_Qualification', models.CharField(max_length=200)),
                ('Recognized_as_a_Research_Guide', models.CharField(max_length=100)),
                ('Years_of_Service_at_MITM', models.CharField(default=0, max_length=10, null=True)),
                ('Staff_ID', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Mail_Id', models.EmailField(max_length=254)),
                ('Contact_No', models.CharField(max_length=10)),
                ('Date_of_joining', models.CharField(max_length=20, null=True)),
                ('Specialization', models.CharField(max_length=100)),
                ('If_yes_Number_of_candidates_being_supervised', models.CharField(max_length=100, null=True)),
                ('total_years', models.IntegerField(null=True)),
            ],
        ),
    ]
