# Generated by Django 4.0.3 on 2022-06-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_half_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='ood',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='scl',
        ),
    ]
