# Generated by Django 4.0.3 on 2022-06-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_remove_leave_cl_remove_leave_ood_remove_leave_scl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='half_day',
            name='cl',
        ),
        migrations.AddField(
            model_name='half_day',
            name='Leave_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
